# Copy and paste this EXACTLY into Streamlit Cloud Secrets
# Go to: https://share.streamlit.io -> Your App -> Settings -> Secrets

GOOGLE_API_KEY = "AIzaSyAsxv4RFEMJkdceaHimHioj6iZSkURT-HE"
APP_NAME = "Bangladesh Legal Assistant"
APP_VERSION = "1.0.0"
DEBUG = false
VECTOR_STORE_PATH = "./vectorstore"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K_RESULTS = 5
LOG_LEVEL = "INFO"
LOG_FILE = "./logs/app.log"